---
version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.yaml'
    volumes:
      - ./instructions:/tmp
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'